name: Docker Builder
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        # GitHub скачивает исходный код Evolution API к себе "домой"
        run: git clone https://github.com/EvolutionAPI/evolution-api.git .

      - name: Build Docker Image
        # Мы строим образ сами! Никаких "Pull denied"
        run: docker build -t evolutionapi/evolution-api:latest .

      - name: Save Image to File
        run: docker save -o evolution.tar evolutionapi/evolution-api:latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: evolution-archive
          path: evolution.tar
