name: Docker Puller
on: [workflow_dispatch]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker pull devopsaurus/waha:latest
          docker save -o waha.tar devopsaurus/waha:latest
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: waha-archive
          path: waha.tar
